version: "3.9"

services:
  db:
    image: postgres:16
    container_name: demo_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppass}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_spring_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "db"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB:-appdb}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER:-appuser}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-apppass}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      JAVA_OPTS: ""
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: unless-stopped

volumes:
  pgdata:
